service: lambda-typescript

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  region: ap-northeast-1
  environment:
    NODE_ENV: ${env:STAGE}
  stage: ${env:STAGE}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test_tbl
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
        StreamSpecification:
          StreamViewType: NEW_IMAGE

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: books
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: books/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: books
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: books/{id}
          method: get

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: books/{id}
          method: delete
  send-email:
    handler: app/handler.sendEmail
    timeout: 120
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::GetAtt:
              - TestTable
              - StreamArn
